name: pr-preview
run-name: Превью

on:
  pull_request

jobs: 
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      - name: Настройка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Сборка и публикация превью
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          dist: _site
          failOnError: true
          teardown: true
          build: |
            npm ci
            npm run build
      - name: Вывод ссылки в консоль
        run: echo "Сайт доступен по ссылке — ${{ steps.preview_step.outputs.preview_url }}"
